name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Install trunk
      run: wget -qO- https://github.com/thedodd/trunk/releases/download/v0.15.0/trunk-x86_64-unknown-linux-gnu.tar.gz | tar -xzf-
      
    - name: Install wasm
      run: rustup target add wasm32-unknown-unknown
      
    - name: Install node dependencies
      working-directory: node_dependencies
      run: yarn
    
    - name: Build
      run: ./trunk build --release
      
    - name: Publish to github pages
      shell: bash
      run: |
        TEMP_DIR=$(mktemp -d)
        mv "./dist" "$TEMP_DIR"
        git switch -c "gh-pages"
        git fetch
        git reset --hard origin/gh-pages
        rm -rf *
        mv "$TEMP_DIR/dist/"* .
        git config user.email "mjzent@csbsju.edu"
        git config user.name "zentavious"
        git add .
        git commit -m "chore: published at $(date)"
        git pull -r origin "gh-pages"
        git push origin "gh-pages"
